name: Cypress Component Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm run install
          
      - name: Build Server
        working-directory: ./server
        run: |
          npm run build
        env:
          MONGODB_URI: mongodb://localhost:27017/Waleed
          
      - name: Build Client
        working-directory: ./client
        run: |
          npm run build
          
      - name: Run Cypress Component Tests
        run: npm run test-component
        env:
          MONGODB_URI: mongodb://localhost:27017/Waleed
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.node-version }}
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 14